// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package to.bnk.api.types;

public interface ProfileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:types.Profile)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string ProfileID = 1[json_name = "profile_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getProfileID();
  /**
   * <code>string ProfileID = 1[json_name = "profile_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getProfileIDBytes();

  /**
   * <code>string FullName = 2[json_name = "fullname", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getFullName();
  /**
   * <code>string FullName = 2[json_name = "fullname", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>string UserName = 3[json_name = "username", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string UserName = 3[json_name = "username", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string BirthDate = 4[json_name = "birthdate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getBirthDate();
  /**
   * <code>string BirthDate = 4[json_name = "birthdate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getBirthDateBytes();

  /**
   * <code>string Language = 5[json_name = "language", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getLanguage();
  /**
   * <code>string Language = 5[json_name = "language", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <code>string Country = 6[json_name = "country", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getCountry();
  /**
   * <code>string Country = 6[json_name = "country", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>string Email = 7[json_name = "email", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string Email = 7[json_name = "email", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>bool EmailVefified = 8[json_name = "email_verified", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  boolean getEmailVefified();

  /**
   * <code>string Mobile = 9[json_name = "mobile", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getMobile();
  /**
   * <code>string Mobile = 9[json_name = "mobile", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getMobileBytes();

  /**
   * <code>string Photo = 10[json_name = "photo", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getPhoto();
  /**
   * <code>string Photo = 10[json_name = "photo", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getPhotoBytes();

  /**
   * <code>string Title = 11[json_name = "title", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string Title = 11[json_name = "title", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>.types.Address PermanentAddress = 12[json_name = "permanent_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  boolean hasPermanentAddress();
  /**
   * <code>.types.Address PermanentAddress = 12[json_name = "permanent_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  to.bnk.api.types.Address getPermanentAddress();

  /**
   * <code>.types.Address ContactAddress = 13[json_name = "contact_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  boolean hasContactAddress();
  /**
   * <code>.types.Address ContactAddress = 13[json_name = "contact_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  to.bnk.api.types.Address getContactAddress();
}
