// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package to.bnk.api.types;

/**
 * Protobuf type {@code types.Profile}
 */
public  final class Profile extends
    com.google.protobuf.GeneratedMessageLite<
        Profile, Profile.Builder> implements
    // @@protoc_insertion_point(message_implements:types.Profile)
    ProfileOrBuilder {
  private Profile() {
    profileID_ = "";
    fullName_ = "";
    userName_ = "";
    birthDate_ = "";
    language_ = "";
    country_ = "";
    email_ = "";
    mobile_ = "";
    photo_ = "";
    title_ = "";
  }
  public static final int PROFILEID_FIELD_NUMBER = 1;
  private java.lang.String profileID_;
  /**
   * <code>string ProfileID = 1[json_name = "profile_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getProfileID() {
    return profileID_;
  }
  /**
   * <code>string ProfileID = 1[json_name = "profile_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProfileIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(profileID_);
  }
  /**
   * <code>string ProfileID = 1[json_name = "profile_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setProfileID(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    profileID_ = value;
  }
  /**
   * <code>string ProfileID = 1[json_name = "profile_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearProfileID() {
    
    profileID_ = getDefaultInstance().getProfileID();
  }
  /**
   * <code>string ProfileID = 1[json_name = "profile_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setProfileIDBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    profileID_ = value.toStringUtf8();
  }

  public static final int FULLNAME_FIELD_NUMBER = 2;
  private java.lang.String fullName_;
  /**
   * <code>string FullName = 2[json_name = "fullname", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getFullName() {
    return fullName_;
  }
  /**
   * <code>string FullName = 2[json_name = "fullname", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFullNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(fullName_);
  }
  /**
   * <code>string FullName = 2[json_name = "fullname", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setFullName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    fullName_ = value;
  }
  /**
   * <code>string FullName = 2[json_name = "fullname", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearFullName() {
    
    fullName_ = getDefaultInstance().getFullName();
  }
  /**
   * <code>string FullName = 2[json_name = "fullname", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setFullNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    fullName_ = value.toStringUtf8();
  }

  public static final int USERNAME_FIELD_NUMBER = 3;
  private java.lang.String userName_;
  /**
   * <code>string UserName = 3[json_name = "username", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getUserName() {
    return userName_;
  }
  /**
   * <code>string UserName = 3[json_name = "username", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(userName_);
  }
  /**
   * <code>string UserName = 3[json_name = "username", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setUserName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    userName_ = value;
  }
  /**
   * <code>string UserName = 3[json_name = "username", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearUserName() {
    
    userName_ = getDefaultInstance().getUserName();
  }
  /**
   * <code>string UserName = 3[json_name = "username", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setUserNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    userName_ = value.toStringUtf8();
  }

  public static final int BIRTHDATE_FIELD_NUMBER = 4;
  private java.lang.String birthDate_;
  /**
   * <code>string BirthDate = 4[json_name = "birthdate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getBirthDate() {
    return birthDate_;
  }
  /**
   * <code>string BirthDate = 4[json_name = "birthdate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBirthDateBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(birthDate_);
  }
  /**
   * <code>string BirthDate = 4[json_name = "birthdate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setBirthDate(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    birthDate_ = value;
  }
  /**
   * <code>string BirthDate = 4[json_name = "birthdate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearBirthDate() {
    
    birthDate_ = getDefaultInstance().getBirthDate();
  }
  /**
   * <code>string BirthDate = 4[json_name = "birthdate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setBirthDateBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    birthDate_ = value.toStringUtf8();
  }

  public static final int LANGUAGE_FIELD_NUMBER = 5;
  private java.lang.String language_;
  /**
   * <code>string Language = 5[json_name = "language", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getLanguage() {
    return language_;
  }
  /**
   * <code>string Language = 5[json_name = "language", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanguageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(language_);
  }
  /**
   * <code>string Language = 5[json_name = "language", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setLanguage(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    language_ = value;
  }
  /**
   * <code>string Language = 5[json_name = "language", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearLanguage() {
    
    language_ = getDefaultInstance().getLanguage();
  }
  /**
   * <code>string Language = 5[json_name = "language", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setLanguageBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    language_ = value.toStringUtf8();
  }

  public static final int COUNTRY_FIELD_NUMBER = 6;
  private java.lang.String country_;
  /**
   * <code>string Country = 6[json_name = "country", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getCountry() {
    return country_;
  }
  /**
   * <code>string Country = 6[json_name = "country", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCountryBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(country_);
  }
  /**
   * <code>string Country = 6[json_name = "country", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setCountry(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    country_ = value;
  }
  /**
   * <code>string Country = 6[json_name = "country", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearCountry() {
    
    country_ = getDefaultInstance().getCountry();
  }
  /**
   * <code>string Country = 6[json_name = "country", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setCountryBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    country_ = value.toStringUtf8();
  }

  public static final int EMAIL_FIELD_NUMBER = 7;
  private java.lang.String email_;
  /**
   * <code>string Email = 7[json_name = "email", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    return email_;
  }
  /**
   * <code>string Email = 7[json_name = "email", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(email_);
  }
  /**
   * <code>string Email = 7[json_name = "email", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setEmail(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    email_ = value;
  }
  /**
   * <code>string Email = 7[json_name = "email", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearEmail() {
    
    email_ = getDefaultInstance().getEmail();
  }
  /**
   * <code>string Email = 7[json_name = "email", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setEmailBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    email_ = value.toStringUtf8();
  }

  public static final int EMAILVEFIFIED_FIELD_NUMBER = 8;
  private boolean emailVefified_;
  /**
   * <code>bool EmailVefified = 8[json_name = "email_verified", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public boolean getEmailVefified() {
    return emailVefified_;
  }
  /**
   * <code>bool EmailVefified = 8[json_name = "email_verified", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setEmailVefified(boolean value) {
    
    emailVefified_ = value;
  }
  /**
   * <code>bool EmailVefified = 8[json_name = "email_verified", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearEmailVefified() {
    
    emailVefified_ = false;
  }

  public static final int MOBILE_FIELD_NUMBER = 9;
  private java.lang.String mobile_;
  /**
   * <code>string Mobile = 9[json_name = "mobile", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getMobile() {
    return mobile_;
  }
  /**
   * <code>string Mobile = 9[json_name = "mobile", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMobileBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mobile_);
  }
  /**
   * <code>string Mobile = 9[json_name = "mobile", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setMobile(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    mobile_ = value;
  }
  /**
   * <code>string Mobile = 9[json_name = "mobile", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearMobile() {
    
    mobile_ = getDefaultInstance().getMobile();
  }
  /**
   * <code>string Mobile = 9[json_name = "mobile", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setMobileBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    mobile_ = value.toStringUtf8();
  }

  public static final int PHOTO_FIELD_NUMBER = 10;
  private java.lang.String photo_;
  /**
   * <code>string Photo = 10[json_name = "photo", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getPhoto() {
    return photo_;
  }
  /**
   * <code>string Photo = 10[json_name = "photo", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhotoBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(photo_);
  }
  /**
   * <code>string Photo = 10[json_name = "photo", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setPhoto(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    photo_ = value;
  }
  /**
   * <code>string Photo = 10[json_name = "photo", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearPhoto() {
    
    photo_ = getDefaultInstance().getPhoto();
  }
  /**
   * <code>string Photo = 10[json_name = "photo", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setPhotoBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    photo_ = value.toStringUtf8();
  }

  public static final int TITLE_FIELD_NUMBER = 11;
  private java.lang.String title_;
  /**
   * <code>string Title = 11[json_name = "title", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <code>string Title = 11[json_name = "title", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <code>string Title = 11[json_name = "title", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setTitle(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    title_ = value;
  }
  /**
   * <code>string Title = 11[json_name = "title", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearTitle() {
    
    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <code>string Title = 11[json_name = "title", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    title_ = value.toStringUtf8();
  }

  public static final int PERMANENTADDRESS_FIELD_NUMBER = 12;
  private to.bnk.api.types.Address permanentAddress_;
  /**
   * <code>.types.Address PermanentAddress = 12[json_name = "permanent_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public boolean hasPermanentAddress() {
    return permanentAddress_ != null;
  }
  /**
   * <code>.types.Address PermanentAddress = 12[json_name = "permanent_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public to.bnk.api.types.Address getPermanentAddress() {
    return permanentAddress_ == null ? to.bnk.api.types.Address.getDefaultInstance() : permanentAddress_;
  }
  /**
   * <code>.types.Address PermanentAddress = 12[json_name = "permanent_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setPermanentAddress(to.bnk.api.types.Address value) {
    if (value == null) {
      throw new NullPointerException();
    }
    permanentAddress_ = value;
    
    }
  /**
   * <code>.types.Address PermanentAddress = 12[json_name = "permanent_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setPermanentAddress(
      to.bnk.api.types.Address.Builder builderForValue) {
    permanentAddress_ = builderForValue.build();
    
  }
  /**
   * <code>.types.Address PermanentAddress = 12[json_name = "permanent_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergePermanentAddress(to.bnk.api.types.Address value) {
    if (value == null) {
      throw new NullPointerException();
    }
    if (permanentAddress_ != null &&
        permanentAddress_ != to.bnk.api.types.Address.getDefaultInstance()) {
      permanentAddress_ =
        to.bnk.api.types.Address.newBuilder(permanentAddress_).mergeFrom(value).buildPartial();
    } else {
      permanentAddress_ = value;
    }
    
  }
  /**
   * <code>.types.Address PermanentAddress = 12[json_name = "permanent_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearPermanentAddress() {  permanentAddress_ = null;
    
  }

  public static final int CONTACTADDRESS_FIELD_NUMBER = 13;
  private to.bnk.api.types.Address contactAddress_;
  /**
   * <code>.types.Address ContactAddress = 13[json_name = "contact_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public boolean hasContactAddress() {
    return contactAddress_ != null;
  }
  /**
   * <code>.types.Address ContactAddress = 13[json_name = "contact_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public to.bnk.api.types.Address getContactAddress() {
    return contactAddress_ == null ? to.bnk.api.types.Address.getDefaultInstance() : contactAddress_;
  }
  /**
   * <code>.types.Address ContactAddress = 13[json_name = "contact_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setContactAddress(to.bnk.api.types.Address value) {
    if (value == null) {
      throw new NullPointerException();
    }
    contactAddress_ = value;
    
    }
  /**
   * <code>.types.Address ContactAddress = 13[json_name = "contact_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setContactAddress(
      to.bnk.api.types.Address.Builder builderForValue) {
    contactAddress_ = builderForValue.build();
    
  }
  /**
   * <code>.types.Address ContactAddress = 13[json_name = "contact_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeContactAddress(to.bnk.api.types.Address value) {
    if (value == null) {
      throw new NullPointerException();
    }
    if (contactAddress_ != null &&
        contactAddress_ != to.bnk.api.types.Address.getDefaultInstance()) {
      contactAddress_ =
        to.bnk.api.types.Address.newBuilder(contactAddress_).mergeFrom(value).buildPartial();
    } else {
      contactAddress_ = value;
    }
    
  }
  /**
   * <code>.types.Address ContactAddress = 13[json_name = "contact_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearContactAddress() {  contactAddress_ = null;
    
  }

  public static to.bnk.api.types.Profile parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.types.Profile parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.types.Profile parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.types.Profile parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.types.Profile parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static to.bnk.api.types.Profile parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static to.bnk.api.types.Profile parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.types.Profile parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static to.bnk.api.types.Profile parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.types.Profile parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static to.bnk.api.types.Profile parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static to.bnk.api.types.Profile parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(to.bnk.api.types.Profile prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code types.Profile}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        to.bnk.api.types.Profile, Builder> implements
      // @@protoc_insertion_point(builder_implements:types.Profile)
      to.bnk.api.types.ProfileOrBuilder {
    // Construct using to.bnk.api.types.Profile.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string ProfileID = 1[json_name = "profile_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getProfileID() {
      return instance.getProfileID();
    }
    /**
     * <code>string ProfileID = 1[json_name = "profile_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProfileIDBytes() {
      return instance.getProfileIDBytes();
    }
    /**
     * <code>string ProfileID = 1[json_name = "profile_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setProfileID(
        java.lang.String value) {
      copyOnWrite();
      instance.setProfileID(value);
      return this;
    }
    /**
     * <code>string ProfileID = 1[json_name = "profile_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearProfileID() {
      copyOnWrite();
      instance.clearProfileID();
      return this;
    }
    /**
     * <code>string ProfileID = 1[json_name = "profile_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setProfileIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setProfileIDBytes(value);
      return this;
    }

    /**
     * <code>string FullName = 2[json_name = "fullname", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getFullName() {
      return instance.getFullName();
    }
    /**
     * <code>string FullName = 2[json_name = "fullname", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFullNameBytes() {
      return instance.getFullNameBytes();
    }
    /**
     * <code>string FullName = 2[json_name = "fullname", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setFullName(
        java.lang.String value) {
      copyOnWrite();
      instance.setFullName(value);
      return this;
    }
    /**
     * <code>string FullName = 2[json_name = "fullname", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearFullName() {
      copyOnWrite();
      instance.clearFullName();
      return this;
    }
    /**
     * <code>string FullName = 2[json_name = "fullname", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setFullNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFullNameBytes(value);
      return this;
    }

    /**
     * <code>string UserName = 3[json_name = "username", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getUserName() {
      return instance.getUserName();
    }
    /**
     * <code>string UserName = 3[json_name = "username", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      return instance.getUserNameBytes();
    }
    /**
     * <code>string UserName = 3[json_name = "username", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setUserName(
        java.lang.String value) {
      copyOnWrite();
      instance.setUserName(value);
      return this;
    }
    /**
     * <code>string UserName = 3[json_name = "username", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearUserName() {
      copyOnWrite();
      instance.clearUserName();
      return this;
    }
    /**
     * <code>string UserName = 3[json_name = "username", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserNameBytes(value);
      return this;
    }

    /**
     * <code>string BirthDate = 4[json_name = "birthdate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getBirthDate() {
      return instance.getBirthDate();
    }
    /**
     * <code>string BirthDate = 4[json_name = "birthdate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBirthDateBytes() {
      return instance.getBirthDateBytes();
    }
    /**
     * <code>string BirthDate = 4[json_name = "birthdate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setBirthDate(
        java.lang.String value) {
      copyOnWrite();
      instance.setBirthDate(value);
      return this;
    }
    /**
     * <code>string BirthDate = 4[json_name = "birthdate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearBirthDate() {
      copyOnWrite();
      instance.clearBirthDate();
      return this;
    }
    /**
     * <code>string BirthDate = 4[json_name = "birthdate", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setBirthDateBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBirthDateBytes(value);
      return this;
    }

    /**
     * <code>string Language = 5[json_name = "language", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getLanguage() {
      return instance.getLanguage();
    }
    /**
     * <code>string Language = 5[json_name = "language", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      return instance.getLanguageBytes();
    }
    /**
     * <code>string Language = 5[json_name = "language", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setLanguage(
        java.lang.String value) {
      copyOnWrite();
      instance.setLanguage(value);
      return this;
    }
    /**
     * <code>string Language = 5[json_name = "language", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearLanguage() {
      copyOnWrite();
      instance.clearLanguage();
      return this;
    }
    /**
     * <code>string Language = 5[json_name = "language", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setLanguageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLanguageBytes(value);
      return this;
    }

    /**
     * <code>string Country = 6[json_name = "country", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getCountry() {
      return instance.getCountry();
    }
    /**
     * <code>string Country = 6[json_name = "country", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryBytes() {
      return instance.getCountryBytes();
    }
    /**
     * <code>string Country = 6[json_name = "country", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setCountry(
        java.lang.String value) {
      copyOnWrite();
      instance.setCountry(value);
      return this;
    }
    /**
     * <code>string Country = 6[json_name = "country", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearCountry() {
      copyOnWrite();
      instance.clearCountry();
      return this;
    }
    /**
     * <code>string Country = 6[json_name = "country", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setCountryBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCountryBytes(value);
      return this;
    }

    /**
     * <code>string Email = 7[json_name = "email", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      return instance.getEmail();
    }
    /**
     * <code>string Email = 7[json_name = "email", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return instance.getEmailBytes();
    }
    /**
     * <code>string Email = 7[json_name = "email", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setEmail(
        java.lang.String value) {
      copyOnWrite();
      instance.setEmail(value);
      return this;
    }
    /**
     * <code>string Email = 7[json_name = "email", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearEmail() {
      copyOnWrite();
      instance.clearEmail();
      return this;
    }
    /**
     * <code>string Email = 7[json_name = "email", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEmailBytes(value);
      return this;
    }

    /**
     * <code>bool EmailVefified = 8[json_name = "email_verified", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public boolean getEmailVefified() {
      return instance.getEmailVefified();
    }
    /**
     * <code>bool EmailVefified = 8[json_name = "email_verified", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setEmailVefified(boolean value) {
      copyOnWrite();
      instance.setEmailVefified(value);
      return this;
    }
    /**
     * <code>bool EmailVefified = 8[json_name = "email_verified", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearEmailVefified() {
      copyOnWrite();
      instance.clearEmailVefified();
      return this;
    }

    /**
     * <code>string Mobile = 9[json_name = "mobile", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getMobile() {
      return instance.getMobile();
    }
    /**
     * <code>string Mobile = 9[json_name = "mobile", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMobileBytes() {
      return instance.getMobileBytes();
    }
    /**
     * <code>string Mobile = 9[json_name = "mobile", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setMobile(
        java.lang.String value) {
      copyOnWrite();
      instance.setMobile(value);
      return this;
    }
    /**
     * <code>string Mobile = 9[json_name = "mobile", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearMobile() {
      copyOnWrite();
      instance.clearMobile();
      return this;
    }
    /**
     * <code>string Mobile = 9[json_name = "mobile", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setMobileBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMobileBytes(value);
      return this;
    }

    /**
     * <code>string Photo = 10[json_name = "photo", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getPhoto() {
      return instance.getPhoto();
    }
    /**
     * <code>string Photo = 10[json_name = "photo", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhotoBytes() {
      return instance.getPhotoBytes();
    }
    /**
     * <code>string Photo = 10[json_name = "photo", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setPhoto(
        java.lang.String value) {
      copyOnWrite();
      instance.setPhoto(value);
      return this;
    }
    /**
     * <code>string Photo = 10[json_name = "photo", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearPhoto() {
      copyOnWrite();
      instance.clearPhoto();
      return this;
    }
    /**
     * <code>string Photo = 10[json_name = "photo", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setPhotoBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPhotoBytes(value);
      return this;
    }

    /**
     * <code>string Title = 11[json_name = "title", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <code>string Title = 11[json_name = "title", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <code>string Title = 11[json_name = "title", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <code>string Title = 11[json_name = "title", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <code>string Title = 11[json_name = "title", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <code>.types.Address PermanentAddress = 12[json_name = "permanent_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public boolean hasPermanentAddress() {
      return instance.hasPermanentAddress();
    }
    /**
     * <code>.types.Address PermanentAddress = 12[json_name = "permanent_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public to.bnk.api.types.Address getPermanentAddress() {
      return instance.getPermanentAddress();
    }
    /**
     * <code>.types.Address PermanentAddress = 12[json_name = "permanent_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setPermanentAddress(to.bnk.api.types.Address value) {
      copyOnWrite();
      instance.setPermanentAddress(value);
      return this;
      }
    /**
     * <code>.types.Address PermanentAddress = 12[json_name = "permanent_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setPermanentAddress(
        to.bnk.api.types.Address.Builder builderForValue) {
      copyOnWrite();
      instance.setPermanentAddress(builderForValue);
      return this;
    }
    /**
     * <code>.types.Address PermanentAddress = 12[json_name = "permanent_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder mergePermanentAddress(to.bnk.api.types.Address value) {
      copyOnWrite();
      instance.mergePermanentAddress(value);
      return this;
    }
    /**
     * <code>.types.Address PermanentAddress = 12[json_name = "permanent_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearPermanentAddress() {  copyOnWrite();
      instance.clearPermanentAddress();
      return this;
    }

    /**
     * <code>.types.Address ContactAddress = 13[json_name = "contact_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public boolean hasContactAddress() {
      return instance.hasContactAddress();
    }
    /**
     * <code>.types.Address ContactAddress = 13[json_name = "contact_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public to.bnk.api.types.Address getContactAddress() {
      return instance.getContactAddress();
    }
    /**
     * <code>.types.Address ContactAddress = 13[json_name = "contact_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setContactAddress(to.bnk.api.types.Address value) {
      copyOnWrite();
      instance.setContactAddress(value);
      return this;
      }
    /**
     * <code>.types.Address ContactAddress = 13[json_name = "contact_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setContactAddress(
        to.bnk.api.types.Address.Builder builderForValue) {
      copyOnWrite();
      instance.setContactAddress(builderForValue);
      return this;
    }
    /**
     * <code>.types.Address ContactAddress = 13[json_name = "contact_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder mergeContactAddress(to.bnk.api.types.Address value) {
      copyOnWrite();
      instance.mergeContactAddress(value);
      return this;
    }
    /**
     * <code>.types.Address ContactAddress = 13[json_name = "contact_address", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearContactAddress() {  copyOnWrite();
      instance.clearContactAddress();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:types.Profile)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new to.bnk.api.types.Profile();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "profileID_",
            "fullName_",
            "userName_",
            "birthDate_",
            "language_",
            "country_",
            "email_",
            "emailVefified_",
            "mobile_",
            "photo_",
            "title_",
            "permanentAddress_",
            "contactAddress_",
          };
          java.lang.String info =
              "\u0000\r\u0000\u0000\u0001\r\r\u0000\u0000\u0000\u0001\u0208\u0002\u0208\u0003\u0208" +
              "\u0004\u0208\u0005\u0208\u0006\u0208\u0007\u0208\b\u0007\t\u0208\n\u0208\u000b\u0208" +
              "\f\t\r\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<to.bnk.api.types.Profile> parser = PARSER;
        if (parser == null) {
          synchronized (to.bnk.api.types.Profile.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<to.bnk.api.types.Profile>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:types.Profile)
  private static final to.bnk.api.types.Profile DEFAULT_INSTANCE;
  static {
    Profile defaultInstance = new Profile();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Profile.class, defaultInstance);
  }

  public static to.bnk.api.types.Profile getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Profile> PARSER;

  public static com.google.protobuf.Parser<Profile> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

